version: '3'
services:
  app:
    container_name: enviroapp
    restart: always
    build: .
    ports:
      - '3040:3040'
    links:
      - mongo
  mongo:
    container_name: mongoenv
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
